<?php

/**
 * Module for ProcessWire that clears cache of descendant pages
 * feature is now in the core!
 * https://processwire.com/blog/posts/processwire-core-updates-pull-requests-and-more-2.5.25/#clear-page-cache-by-matching-pages-with-custom-selector
 *
 */

class ClearCacheForSitemap extends WireData implements Module {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire abnum them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {

        return array(
            'title' => 'Clear cache for sitemap', 
            'version' => 1, 
            'summary' => 'Deletes cache (PW MarkupCache) for sitemap after PageSave',
            'singular' => true, 
            'autoload' => true, 
            'icon' => 'unlock',
            );
    }

    /**
     * Initialize the module
     *
     * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
     * when ProcessWire's API is ready. As a result, this is a good place to attach hooks. 
     *
     */
    public function init() {
        $this->pages->addHookAfter('saveReady', $this, 'clearCache');
    }

    /**
     * clear cache for all descendant pages
     *
     */
    public function clearCache($event) {

        $pageRender = wire("modules")->get("PageRender");
        $cacheFile = $pageRender->getCacheFile($pages->get('/sitemap'));
        $cacheFile->remove();
        
        $this->message('Deleted cache for sitemap');

    }

}
